ASDA/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from ASDA import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('ASDAWebApp.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^forms/', include('forms.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),

    # url(r'^forms/', include('forms.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ASDAWebApp/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from ASDA import settings
from django.views.decorators.csrf import csrf_exempt
from ASDAWebApp.views import Index, BookClubView, CommunityServiceView, HealthView, FundraisingView, PrediatricView, SocialView, LunchView, SustainabilityView, VendorRelationsView, GalleryView, PreDentalView

urlpatterns = [
    url(r'^$', Index.as_view(), name='Index'),
    url(r'^committees/$', TemplateView.as_view(
        template_name='ASDAWebApp/Committees/Committees.html'),
        name='Committees'),
    url(r'^calendar/$', TemplateView.as_view(
        template_name='ASDAWebApp/Calendar/calendar.html'),
        name='Calendar'),
    url(r'^pictures/$', GalleryView.as_view(),
        name='Pictures'),
    url(r'^committees/bookclub/$', BookClubView.as_view(),
        name='BookClubView'),
    url(r'^committees/communityservice/$', CommunityServiceView.as_view(),
        name='CommunityServiceView'),
    url(r'^committees/health/$', HealthView.as_view(),
        name='HealthView'),
    url(r'^committees/fundraising/$', FundraisingView.as_view(),
        name='FundraisingView'),
    url(r'^committees/specialty/$', PrediatricView.as_view(),
        name='specialtyView'),
    url(r'^committees/social/$', SocialView.as_view(),
        name='SocialView'),
    url(r'^committees/lunch/$', LunchView.as_view(),
        name='LunchView'),
    url(r'^committees/sustainability/$', SustainabilityView.as_view(),
        name='SustainabilityView'),
    url(r'^committees/vendorrelations/$', VendorRelationsView.as_view(),
        name='VendorRelationsView'),
    url(r'^committees/predental/$', PreDentalView.as_view(),
        name='PreDentalView'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from django.views.generic import ListView, DetailView
from blog.models import BlogPost
from blog.views import blogPostList, blogTagQueryList, postDetail


urlpatterns = [url(r'^$', blogPostList.as_view(), name="blogPostList"),
               url(r'^(?P<pk>\d+$)', postDetail.as_view()),
               url(r'^tags/(?P<tag>\w+)/$', blogTagQueryList.as_view(),
                   name="blogTagQueryList")]


#    ListView.as_view(
#                        queryset=BlogPost.objects.filter(approved=True).order_by("-date")[:10],
#                        template_name="blog/blog.html"))

ASDAWebApp/models.py
from django.db import  models

# Create your models here.

forms/models.py
from django.db import models
from django.utils.encoding import smart_text


class contactUs(models.Model):
    name = models.CharField(max_length=140, null=True, blank=True)
    email = models.EmailField()
    subject = models.CharField(max_length=140, null=True, blank=True)
    message = models.TextField()

    class Meta:
        verbose_name = 'Contact Request'
        verbose_name_plural = 'Contact Requests'

    def __str__(self):
        return self.email


class PreDentalSignUp(models.Model):
    name = models.CharField(max_length=140)
    Phone = models.CharField(max_length=30)
    Address1 = models.CharField(max_length=140)
    Address2 = models.CharField(max_length=140)
    Email = models.CharField(max_length=70)
    Gender = models.CharField(max_length=20)
    BirthDate = models.CharField(max_length=20)

    School = models.CharField(max_length=140)
    Year = models.CharField(max_length=140)

    EmergName = models.CharField(max_length=140)
    EmergPhone = models.CharField(max_length=30)
    EmergEmail = models.CharField(max_length=70)

    SocialEvent = models.CharField(max_length=10)
    DietaryNeeds = models.CharField(max_length=200)
    NeedHotel = models.BooleanField(default=False)

    Verified = models.BooleanField(default=False)

    def __str__(self):
        return self.name

ASDAWebApp/views.py
from django.shortcuts import render
from blog.models import BlogPost, BlogImage
from forms.models import contactUs, PreDentalSignUp
from django.views.generic import ListView, CreateView
from forms.AsdaForms import ContactUsForm
import json
from datetime import datetime
from django.views.decorators.csrf import csrf_exempt
import csv


class Index(CreateView):
    form_class = ContactUsForm
    model = contactUs
    success_url = '/'
    template_name = "ASDAWebApp/Home/Index.html"

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['recentPosts'] = BlogPost.objects.filter(
                                 approved=True).order_by('-date')[:4]
        return context

    def form_valid(self, form):
        form.save()
        return super(Index, self).form_valid(form)


class BookClubView(ListView):
    model = BlogPost
    template_name = "ASDAWebApp/Committees/BookClub.html"
    queryset = BlogPost.objects.filter(tags__name='BookClub',
                                       approved=True).order_by("-date")[:4]


class GalleryView(ListView):
    model = BlogImage
    template_name = "ASDAWebApp/Pictures.html"
    images = BlogImage.objects.filter(blogPost__approved=True).order_by('-id')
    queryset = images


class CommunityServiceView(ListView):
    model = BlogPost
    template_name = "ASDAWebApp/Committees/CommunityService.html"
    queryset = BlogPost.objects.filter(tags__name='CommunityService',
                                       approved=True).order_by("-date")[:4]


class VendorRelationsView(ListView):
    model = BlogPost
    template_name = "ASDAWebApp/Committees/VendorRelations.html"
    queryset = BlogPost.objects.filter(tags__name='VendorRelations',
                                       approved=True).order_by("-date")[:4]


class HealthView(ListView):
    model = BlogPost
    template_name = "ASDAWebApp/Committees/Health.html"
    queryset = BlogPost.objects.filter(tags__name='HealthAndWellness',
                                       approved=True).order_by("-date")[:4]


class FundraisingView(ListView):
    model = BlogPost
    template_name = "ASDAWebApp/Committees/FundraisingCommittee.html"
    queryset = BlogPost.objects.filter(tags__name='Fundraising',
                                       approved=True).order_by("-date")[:4]


class PrediatricView(ListView):
    model = BlogPost
    template_name = "ASDAWebApp/Committees/PediatricCommittee.html"
    queryset = BlogPost.objects.filter(tags__name='Pediatrics',
                                       approved=True).order_by("-date")[:4]


class SocialView(ListView):
    model = BlogPost
    template_name = "ASDAWebApp/Committees/SocialCommittee.html"
    queryset = BlogPost.objects.filter(tags__name='Social',
                                       approved=True).order_by("-date")[:4]


class LunchView(ListView):
    model = BlogPost
    template_name = "ASDAWebApp/Committees/LunchClub.html"
    queryset = BlogPost.objects.filter(tags__name='Lunch',
                                       approved=True).order_by("-date")[:4]


class SustainabilityView(ListView):
    model = BlogPost
    template_name = "ASDAWebApp/Committees/SustainabilityCommittee.html"
    queryset = BlogPost.objects.filter(tags__name='Sustainability',
                                       approved=True).order_by("-date")[:4]


class PreDentalView(ListView):
    model = BlogPost
    template_name = "ASDAWebApp/Committees/PreDental.html"
    queryset = BlogPost.objects.filter(tags__name='PreDental',
                                       approved=True).order_by("-date")[:4]

ASDAWebApp/templates/ASDAWebApp/Calendar/calendar.html
{% extends "ASDAWebApp/Generic/navBar.html"%}
{% block content %}
{% load staticfiles %}

<div id="fh5co-hero"  class="container"  style="background-image: url({% static 'img/marquettebuilding.jpg' %});">
	<div class="overlay"></div>
	<div class="row">
		<div class="col-md-12">
			<div class="fh5co-hero-wrap">
				<div class="fh5co-hero-intro">
					<h1 class="to-animate hero-animate-1">WE ARE <span class="gold bold">#MARQUETTEASDA</span></h1>
					<p class="to-animate hero-animate-2">Check Out Whats Coming Up</p>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="fh5co-main">
  <div class="container-fluid white-background">
    <br>
    <div class="row">
      <div class="col-sm-12 heading text-center"><h2>Calendar</h2></div>
    </div>
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1" id='calendar'></div>
    </div>
  </div>
</div>

{% include "ASDAWebApp/Calendar/calendarFooter.html" %}
{% endblock %}

ASDAWebApp/templates/ASDAWebApp/Calendar/calendarFooter.html
{% load staticfiles %}
{% load formFilters %}
<footer role="contentinfo" id="fh5co-footer">
	<a href="#" class="fh5co-arrow fh5co-gotop footer-box"><i class="ti-angle-up"></i></a>
	<div class="container">
		<div class="row">
			<div class="col-md-7 col-sm-12 footer-box">
				<h3 class="fh5co-footer-heading">FIND US</h3>
				<a href="http://maps.google.com/?q=1801 W. Wisconsin Ave Milwaukee, WI 53233" target="_blank">
					<div class="address">
						<p>Marquette School of Dentistry</p>
						<p>1801 W. Wisconsin Ave</p>
						<p>Milwaukee, WI 53233</p>
					</div>
				</a>
				<div class="mapholder">
					<div id="map"></div>
				</div>
			</div>
			<div class="col-md-5 col-sm-12 footer-box">
			<div class="fh5co-main-height50 visible-xs-block visible-sm-block"><!--This looks nicer for mobile.-Keith Hetzel--></div>
				<h3 class="fh5co-footer-heading">CONTACT</h3>
				<div>
					<p><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> 414.288.6790</p>
				  <p><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> MarquetteASDA@gmail.com</p>
				</div>
				<!--<form method=POST>
					{% csrf_token %}
					{% for field in form %}
					  <div class="form-group row">

							<div class="col-xs-12">
								{{field|addclass:'col-xs-12 form-control'}}
						    {{field.errors}}
							</div>
					  </div>
					{% endfor %}
					<input value="Submit" type="submit" class="btn btn-outline btn-md"/>
				</form>-->
				<form method=POST>
					{% csrf_token %}
				  <div class="form-group row">
						<div class="col-xs-12">
								<input class="col-xs-12 form-control marginBottom30" id="id_name" maxlength="140" name="name" placeholder="name" type="text">
								<input class="col-xs-12 form-control marginBottom30" id="id_email" maxlength="140" name="email" placeholder="email" type="text">
								<input class="col-xs-12 form-control marginBottom30" id="id_subject" maxlength="140" name="subject" placeholder="subject" type="text">
								<textarea class="col-xs-12 form-control" cols="15" id="id_message" name="message" placeholder="message" rows="4" required=""></textarea>
						</div>
				  </div>
					<input value="Submit" type="submit" class="btn btn-outline btn-md"/>
				</form>
  		</div>
  	</div>

	<div class="row">
		<div class="col-md-7 col-sm-12 footer-box">
		<div class="fh5co-main-height50 visible-xs-block visible-sm-block"><!--This looks nicer for mobile.-Keith Hetzel--></div>
			<h3 class="fh5co-footer-heading">Get in touch</h3>
			<ul class="fh5co-social-icons">
				<li><a href="https://plus.google.com/u/0/111559584108125364001/posts"><i class="ti-google"></i></a></li>
				<li><a href="https://twitter.com/marquetteasda"><i class="ti-twitter-alt"></i></a></li>
				<li><a href="https://www.facebook.com/MarquetteASDA"><i class="ti-facebook"></i></a></li>
				<li><a href="https://www.instagram.com/marquetteasda/"><i class="ti-instagram"></i></a></li>
				<li><a href="https://www.youtube.com/user/marquetteasda"><i class="ti-youtube"></i></a></li>
			</ul>
		</div>

	  <div class="col-md-5 col-sm-12 footer-box">
	    <div class"copyrightFooter">
			<div class="fh5co-main-height50 visible-xs-block visible-sm-block"><!--This looks nicer for mobile.-Keith Hetzel--></div>
	    <p>Copyright &copy; Marquette 2016<br>Designed by Raymond Cisneros &amp; Keith Hetzel</p>
	    </div>
	  </div>
	</div>
</footer>

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/parallax.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/hoverIntent.js' %}"></script>
<script type="text/javascript" src="{% static 'js/superfish.js' %}"></script>
<script type="text/javascript" src="{% static 'js/easyResponsiveTabs.js' %}"></script>
<script type="text/javascript" src="{% static 'js/fastclick.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.parallax-scroll.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>

<!--These are the calendar files-->
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/fullcalendar.min.js' %}"></script>
<script src="{% static 'js/gcal.min.js' %}"></script>

<script>
  //this is for when the page loads, it will scroll up 10px so the navBar loads
  $(document).ready(function() {
    $(window).scrollTop(($(window).scrollTop())-10);
  });
</script>

<script>
$(document).ready(function() {
    $('#calendar').fullCalendar({
        googleCalendarApiKey: 'AIzaSyBgEuhJO2HhnASoUblE55UF_SnPRUbmeJs',
        events: {
            googleCalendarId: 'marquetteasda@gmail.com'
        }
    });
});
</script>

<script>
  var map;
  function initMap() {
		var marquette = {lat: 43.038188, lng: -87.936039};
    map = new google.maps.Map(document.getElementById('map'), {
      center: marquette,
      zoom: 14,
			styles: [
					  {
					    "elementType": "geometry",
					    "stylers": [
					      {
					        "color": "#ebe3cd"
					      }
					    ]
					  },
					  {
					    "elementType": "labels.text.fill",
					    "stylers": [
					      {
					        "color": "#523735"
					      }
					    ]
					  },
					  {
					    "elementType": "labels.text.stroke",
					    "stylers": [
					      {
					        "color": "#f5f1e6"
					      }
					    ]
					  },
					  {
					    "featureType": "administrative",
					    "elementType": "geometry.stroke",
					    "stylers": [
					      {
					        "color": "#c9b2a6"
					      }
					    ]
					  },
					  {
					    "featureType": "administrative.land_parcel",
					    "elementType": "geometry.stroke",
					    "stylers": [
					      {
					        "color": "#dcd2be"
					      }
					    ]
					  },
					  {
					    "featureType": "administrative.land_parcel",
					    "elementType": "labels.text.fill",
					    "stylers": [
					      {
					        "color": "#ae9e90"
					      }
					    ]
					  },
					  {
					    "featureType": "landscape.natural",
					    "elementType": "geometry",
					    "stylers": [
					      {
					        "color": "#dfd2ae"
					      }
					    ]
					  },
					  {
					    "featureType": "poi",
					    "elementType": "geometry",
					    "stylers": [
					      {
					        "color": "#dfd2ae"
					      }
					    ]
					  },
					  {
					    "featureType": "poi",
					    "elementType": "labels.text.fill",
					    "stylers": [
					      {
					        "color": "#93817c"
					      }
					    ]
					  },
					  {
					    "featureType": "poi.business",
					    "stylers": [
					      {
					        "visibility": "off"
					      }
					    ]
					  },
					  {
					    "featureType": "poi.park",
					    "elementType": "geometry.fill",
					    "stylers": [
					      {
					        "color": "#a5b076"
					      }
					    ]
					  },
					  {
					    "featureType": "poi.park",
					    "elementType": "labels.text",
					    "stylers": [
					      {
					        "visibility": "off"
					      }
					    ]
					  },
					  {
					    "featureType": "poi.park",
					    "elementType": "labels.text.fill",
					    "stylers": [
					      {
					        "color": "#447530"
					      }
					    ]
					  },
					  {
					    "featureType": "poi.place_of_worship",
					    "stylers": [
					      {
					        "visibility": "off"
					      }
					    ]
					  },
					  {
					    "featureType": "road",
					    "elementType": "geometry",
					    "stylers": [
					      {
					        "color": "#f5f1e6"
					      }
					    ]
					  },
					  {
					    "featureType": "road.arterial",
					    "elementType": "geometry",
					    "stylers": [
					      {
					        "color": "#fdfcf8"
					      }
					    ]
					  },
					  {
					    "featureType": "road.highway",
					    "elementType": "geometry",
					    "stylers": [
					      {
					        "color": "#f8c967"
					      }
					    ]
					  },
					  {
					    "featureType": "road.highway",
					    "elementType": "geometry.stroke",
					    "stylers": [
					      {
					        "color": "#e9bc62"
					      }
					    ]
					  },
					  {
					    "featureType": "road.highway.controlled_access",
					    "elementType": "geometry",
					    "stylers": [
					      {
					        "color": "#e98d58"
					      }
					    ]
					  },
					  {
					    "featureType": "road.highway.controlled_access",
					    "elementType": "geometry.stroke",
					    "stylers": [
					      {
					        "color": "#db8555"
					      }
					    ]
					  },
					  {
					    "featureType": "road.local",
					    "elementType": "labels.text.fill",
					    "stylers": [
					      {
					        "color": "#806b63"
					      }
					    ]
					  },
					  {
					    "featureType": "transit.line",
					    "elementType": "geometry",
					    "stylers": [
					      {
					        "color": "#dfd2ae"
					      }
					    ]
					  },
					  {
					    "featureType": "transit.line",
					    "elementType": "labels.text.fill",
					    "stylers": [
					      {
					        "color": "#8f7d77"
					      }
					    ]
					  },
					  {
					    "featureType": "transit.line",
					    "elementType": "labels.text.stroke",
					    "stylers": [
					      {
					        "color": "#ebe3cd"
					      }
					    ]
					  },
					  {
					    "featureType": "transit.station",
					    "elementType": "geometry",
					    "stylers": [
					      {
					        "color": "#dfd2ae"
					      }
					    ]
					  },
					  {
					    "featureType": "water",
					    "elementType": "geometry.fill",
					    "stylers": [
					      {
					        "color": "#b9d3c2"
					      }
					    ]
					  },
					  {
					    "featureType": "water",
					    "elementType": "labels.text.fill",
					    "stylers": [
					      {
					        "color": "#92998d"
					      }
					    ]
					  }
					]
    });
		var image = '{% static 'img/pointer.png' %}';
    var marker = new google.maps.Marker({
      position: marquette,
			title:"Marquette School of Dentistry",
      map: map,
			icon: image
    });

  }
</script>
   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA6kp0RNXLLqTtlZTScexKXQ97PZe8GBv0&callback=initMap" async defer></script>
<script>
$('.bg-holder').parallaxScroll({
  friction: 0.5
});
</script>
</html>